# permissions for end users to view bitwardensecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bitwardensecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sm-operator
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
  name: bitwardensecret-viewer-role
rules:
- apiGroups:
  - k8s.bitwarden.com
  resources:
  - bitwardensecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.bitwarden.com
  resources:
  - bitwardensecrets/status
  verbs:
  - get
