apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "a08a8157-129e-4002-bab4-b118014ca9c7"
  projects:
    - projectId: 9e10d82c-148e-42f9-8ae6-b11b00eec806
      secretName: bw-sample-secret
      map:
      - bwSecretId: 6c230265-d472-45f7-b763-b11b01023ca6
        secretKeyName: test__secret__1
      - bwSecretId: d132a5ed-12bd-49af-9b74-b11b01025d58
        secretKeyName: test__secret__2
    - projectId: 9e10d82c-148e-42f9-8ae6-b11b00ee1234
      secretName: bw-sample-secret2
      map:
      - bwSecretId: 6c230265-d472-45f7-b763-b11b01023ca6
        secretKeyName: test__secret__3
      - bwSecretId: d132a5ed-12bd-49af-9b74-b11b01025d58
        secretKeyName: test__secret__4
  authToken:
    secretName: bw-auth-token
    secretKey: token
